# Site
name: "Po's Blog"
description: "My pretty awesome blog or so"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/img/logo.svg'
favicon: 'assets/img/favicon.ico'
# baseurl: /
google_analytics: 'UA-122600677-2'
# disqus: 'blog.phohuynh.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  po:
    name: Po
    display_name: Po Béo
    gravatar: 22b726d6f21d9199ee9dc60df6d99c75
    email: shortgiraffe4@gmail.com
    web: https://phohuynh.com
    twitter: https://twitter.com/shortgiraffe4
    description: "A web developer"
  meobeoi:
    name: TrungNM
    display_name: Mèo Béo Ị
    gravatar: 708a3f186fd7f6eb4237c93cd4fd7836
    email: nguyenminhtrung0512@gmail.com
    description: "A Cat"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge